name: Build, Test, and Deploy Unity Project

on: [push, pull_request]

jobs:
  # Job to build the StandaloneWindows64 platform
  buildWindows:
    name: Build StandaloneWindows64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows64-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-StandaloneWindows64-
            Library-

      - name: Free disk space (optional)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64

  # Job to run Playmode tests
  runPlaymodeTests:
    name: Run Playmode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-PlaymodeTests-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-PlaymodeTests-
            Library-

      - name: Run Unity Playmode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: PlayMode
          # The path where test results will be generated
          artifactsPath: artifacts/TestResults/Playmode

      - name: Upload Playmode Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Playmode-Test-Results
          path: artifacts/TestResults/Playmode

  # Job to deploy the build to GitHub Releases
  deployToGitHubReleases:
    name: Deploy to GitHub Releases
    runs-on: ubuntu-latest
    needs: buildWindows # This job depends on the buildWindows job completing successfully
    if: startsWith(github.ref, 'refs/tags/') # Only run this job when a tag is pushed

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: ./build/StandaloneWindows64 # Path where the artifact will be downloaded

      - name: Archive Build Folder
        run: tar -czvf build/StandaloneWindows64.tar.gz -C build/ StandaloneWindows64
        # This command creates a gzipped tar archive of the StandaloneWindows64 folder.
        # -C build/ changes the directory to 'build/' before archiving,
        # ensuring 'StandaloneWindows64' is at the root of the archive.
        # The archive will be named 'StandaloneWindows64.tar.gz' and placed in the 'build/' directory.

  # Job to upload release to Google Drive
  uploadToGoogleDrive:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: buildWindows # This job depends on the buildWindows job completing successfully

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: Build-StandaloneWindows64
        path: ./build/StandaloneWindows64 # Path where the artifact will be downloaded
    - name: Compress to 7z archive
      uses: edgarrc/action-7z@v1
      with:
        args: 7z -t7z -mx=7 StandaloneWindows64.7z StandaloneWindows64
    - name: Upload Artifacts To Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.3.1
      with:
        target: Build-StandaloneWindows64.7z
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        parent_folder_id: ${{ vars.GOOGLE_DRIVE_FOLDER_ID }}
        override: true
        owner: ${{ secrets.UNITY_EMAIL }}
        replace_mode: update_in_place